version: '3.8'

services:
  audio_processor:
    build: .
    volumes:
      - ./input:/app/input
      - ./output:/app/output
      - ./asr:/app/asr
    env_file:
      - .env
    command: python main.py
