version: '3.8'

services:
  converter:
    build: .
    volumes:
      - ./input:/app/input
      - ./output:/app/output
    environment:
      - SPLIT_DURATION=${SPLIT_DURATION:-0}
    command: python main.py
